Backend default tolerance
TIS2022-FMFI/weight-inspection pull request #110
Opened 2023-01-21 20:47 UTC by warmac9

2023-01-21 22:18 UTC, letenay7 requested changes
Nerozumiem path variable emailId v get requeste notification asi by si ju mal vymazat. bez toho to funguje
inak ok

2023-01-22 22:33 UTC, warmac9 commented
Chybu som opravil

2023-01-23 09:02 UTC, letenay7 submitted a review, later dismissed
ok

2023-01-23 12:10 UTC, letenay7 approved these changes
vsetko funguje ok

2023-01-23 12:10 UTC, merged